#
default: &default
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['POSTGRES_NAME'] %>
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default